apiVersion: v1
kind: Service                # Service resource type
metadata:
  name: grafana             # Service name for DNS lookup
  namespace: monitoring     # Kubernetes namespace
spec:
  type: NodePort           # Expose service on each Node's IP at a static port
  ports:
  - port: 3000            # Port exposed internally in the cluster
    targetPort: 3000      # Port the container is listening on
    nodePort: 30300       # Port exposed externally on the Node (must be >30000)
    protocol: TCP         # Network protocol
  selector:
    app: grafana          # Select pods with label app=grafana
