apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.20.3
        command: ["mlflow", "server"]
        args:
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "5000"
          - "--backend-store-uri"
          - "file:///mlflow/storage"
          - "--default-artifact-root"
          - "file:///mlflow/storage/artifacts"
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: mlflow-config
        volumeMounts:
        - name: mlflow-storage
          mountPath: /mlflow/storage
      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: mlflow-pvc
