apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_ENV: production
  APP_DEBUG: "false"
---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "echo $(APP_ENV) && sleep 3600"]
      envFrom:
        - configMapRef:
            name: app-config
